# Generated by Django 5.0.14 on 2026-01-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='transfer_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='transfer_history',
            field=models.JSONField(blank=True, default=list, help_text='History of school transfers [{school_id, school_name, from_date, to_date}]'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='transfer_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected'), ('resigned', 'Resigned'), ('transfer_requested', 'Transfer Requested')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'School Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=20),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text="Unique school code (e.g., 'ABC', 'XYZ')", max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('school_verification_code', models.CharField(help_text='Unique code for teacher self-registration', max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, help_text='Board affiliation (e.g., CBSE, ICSE)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
            },
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='transfer_requested_to',
            field=models.ForeignKey(blank=True, help_text='School teacher has requested to transfer to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfer_requests', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this user belongs to. NULL for super admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.school'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['transfer_requested_to'], name='teacher_pro_transfe_6cd67a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school'], name='users_school__965c22_idx'),
        ),
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['code'], name='schools_code_adc256_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['status'], name='schools_status_0f17fc_idx'),
        ),
    ]
