# Generated by Django 5.0.14 on 2026-01-20 04:22

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0005_section_class_teacher"),
        ("accounts", "0002_remove_schoolprofile_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects this teacher is qualified to teach",
                related_name="teachers",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otp_verification",
                "indexes": [
                    models.Index(
                        fields=["user", "otp"], name="otp_verific_user_id_753969_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="otp_verific_expires_b46ee7_idx"
                    ),
                ],
            },
        ),
    ]
