# Generated by Django 5.0.14 on 2026-01-28 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_managers_teacherprofile_subjects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
