# Generated by Django 5.0.14 on 2026-01-15 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission_number",
                    models.CharField(
                        help_text="e.g., 'ADM2024001'", max_length=50, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                (
                    "aadhaar_number",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("admission_date", models.DateField()),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("previous_class", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="students",
                        to="academic.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="students",
                        to="academic.section",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
                "db_table": "student_profiles",
            },
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary contact for communications"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Profile",
                "verbose_name_plural": "Parent Profiles",
                "db_table": "parent_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["admission_number"], name="student_pro_admissi_3e761b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["class_obj", "section"], name="student_pro_class_o_69be4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["email"], name="student_pro_email_afb72e_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["phone"], name="student_pro_phone_c3cbc7_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["status"], name="student_pro_status_44d5f8_idx"),
        ),
        migrations.AddIndex(
            model_name="parentprofile",
            index=models.Index(
                fields=["student"], name="parent_prof_student_1a2cca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentprofile",
            index=models.Index(
                fields=["relation"], name="parent_prof_relatio_2685c9_idx"
            ),
        ),
    ]
