# Generated by Django 5.0.14 on 2026-01-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_class_classes_code_674040_idx_and_more'),
        ('accounts', '0002_remove_schoolprofile_updated_by_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this student belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='transfer_history',
            field=models.JSONField(blank=True, default=list, help_text='History of school transfers'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(help_text="e.g., 'ADM2024001'", max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('school', 'admission_number'), ('school', 'email'), ('school', 'phone')},
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['school'], name='student_pro_school__ed3de5_idx'),
        ),
    ]
