# Generated by Django 5.0.14 on 2026-01-20 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_managers_teacherprofile_subjects_and_more"),
        ("students", "0004_parentprofile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="aadhar_card",
            field=models.FileField(
                blank=True, null=True, upload_to="students/documents/"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="birth_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="students/documents/"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="bus_route",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="caste",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="caste_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="students/documents/"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("obc", "OBC"),
                    ("sc", "SC"),
                    ("st", "ST"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in cm",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="hostel_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="hostel_room_preference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="medical_conditions",
            field=models.TextField(
                blank=True, help_text="Any chronic conditions or disabilities"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="mother_tongue",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="nationality",
            field=models.CharField(default="Indian", max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="students/photos/"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="pickup_point",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="previous_marks",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Previous percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="religion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="roll_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="tc_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="tc_number",
            field=models.CharField(
                blank=True, help_text="Transfer Certificate number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="transfer_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="students/documents/"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="transport_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="vaccination_status",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kg",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AdmissionFormConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field_name",
                    models.CharField(
                        help_text="Internal field name (e.g., 'middle_name', 'religion')",
                        max_length=100,
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        help_text="Display label for the field", max_length=200
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("email", "Email"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("textarea", "Textarea"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("checkbox", "Checkbox"),
                            ("decimal", "Decimal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Information"),
                            ("personal", "Personal Information"),
                            ("contact", "Contact Information"),
                            ("emergency", "Emergency Contact"),
                            ("medical", "Medical Information"),
                            ("academic", "Academic Information"),
                            ("documents", "Documents"),
                            ("transport", "Transport"),
                            ("hostel", "Hostel"),
                            ("parent", "Parent Information"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Show this field in the form"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Make this field mandatory"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order within section (lower = first)"
                    ),
                ),
                ("help_text", models.CharField(blank=True, max_length=500)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='For select/radio fields: [{"value": "male", "label": "Male"}]',
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional validation rules",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="School this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.school",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Form Configuration",
                "verbose_name_plural": "Admission Form Configurations",
                "db_table": "admission_form_configs",
                "ordering": ["section", "display_order", "field_name"],
                "indexes": [
                    models.Index(
                        fields=["school", "section"],
                        name="admission_f_school__74fa90_idx",
                    ),
                    models.Index(
                        fields=["school", "is_visible"],
                        name="admission_f_school__fe250e_idx",
                    ),
                ],
                "unique_together": {("school", "field_name")},
            },
        ),
    ]
