# Generated by Django 5.0.14 on 2026-01-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "students",
            "0005_studentprofile_aadhar_card_studentprofile_allergies_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="admission_number",
            field=models.CharField(
                db_index=True, help_text="e.g., 'ADM2024001'", max_length=50
            ),
        ),
    ]
