# Generated by Django 5.0.14 on 2026-01-15 04:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Mid-Term Exam 2024'", max_length=200
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("unit_test", "Unit Test"),
                            ("mid_term", "Mid-Term"),
                            ("final", "Final"),
                            ("annual", "Annual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("academic_year", models.CharField(max_length=10)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "db_table": "exams",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=5,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_results_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="students.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Result",
                "verbose_name_plural": "Exam Results",
                "db_table": "exam_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["academic_year"], name="exams_academi_aac429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["status"], name="exams_status_863d01_idx"),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(fields=["exam"], name="exam_result_exam_id_14ebd6_idx"),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["student"], name="exam_result_student_836d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["subject"], name="exam_result_subject_3935ac_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together={("exam", "student", "subject")},
        ),
    ]
