# Generated by Django 5.0.14 on 2026-01-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_class_unique_together_and_more'),
        ('accounts', '0002_remove_schoolprofile_updated_by_and_more'),
        ('exams', '0001_initial'),
        ('students', '0002_studentprofile_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exam',
            name='exams_academi_aac429_idx',
        ),
        migrations.RemoveIndex(
            model_name='examresult',
            name='exam_result_exam_id_14ebd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='examresult',
            name='exam_result_student_836d1a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='school',
            field=models.ForeignKey(blank=True, help_text="Auto-populated from exam's school", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='accounts.school'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('school', 'exam', 'student', 'subject')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'academic_year'], name='exams_school__99de6b_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['school', 'exam'], name='exam_result_school__457abe_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['school', 'student'], name='exam_result_school__47aead_idx'),
        ),
    ]
