# Generated by Django 5.0.14 on 2026-01-29 04:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0007_remove_class_classes_status_ae471a_idx_and_more"),
        ("accounts", "0005_alter_school_created_by_alter_school_updated_by"),
        ("exams", "0002_remove_exam_exams_academi_aac429_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Schedule",
                "verbose_name_plural": "Exam Schedules",
                "db_table": "exam_schedules",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="class_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="academic.class",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["class_obj"], name="exams_class_o_f43e5b_idx"),
        ),
        migrations.AddField(
            model_name="examschedule",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="exams.exam",
            ),
        ),
        migrations.AddField(
            model_name="examschedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_schedules",
                to="academic.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examschedule",
            unique_together={("exam", "subject")},
        ),
    ]
