# Generated by Django 5.0.14 on 2026-01-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_class_unique_together_and_more'),
        ('accounts', '0002_remove_schoolprofile_updated_by_and_more'),
        ('attendance', '0001_initial'),
        ('students', '0002_studentprofile_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance_student_5b1d70_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance_date_d460ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance_class_o_133496_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance_date_93f4f7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(blank=True, help_text="Auto-populated from student's school", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.school'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('school', 'student', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school', 'student'], name='attendance_school__ded34d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school', 'date'], name='attendance_school__ee2cee_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school', 'class_obj', 'section'], name='attendance_school__ee83d1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school', 'date', 'class_obj', 'section'], name='attendance_school__7cf8f6_idx'),
        ),
    ]
