# Generated by Django 5.0.14 on 2026-01-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_class_unique_together_and_more'),
        ('accounts', '0002_remove_schoolprofile_updated_by_and_more'),
        ('fees', '0001_initial'),
        ('students', '0002_studentprofile_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feestructure',
            name='fee_structu_class_o_b9d694_idx',
        ),
        migrations.RemoveIndex(
            model_name='feestructure',
            name='fee_structu_academi_fa238e_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_student_a32263_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_invoice_7778bc_idx',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='class_obj',
            field=models.ForeignKey(blank=True, help_text='NULL = applicable to all classes in the school', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fee_structures', to='academic.class'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(help_text="e.g., 'INV-2024-001'", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('school', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'class_obj'], name='fee_structu_school__92ee03_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'academic_year'], name='fee_structu_school__3fabf1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'student'], name='invoices_school__9f84a3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'invoice_number'], name='invoices_school__c8bf18_idx'),
        ),
    ]
