# Generated by Django 5.0.14 on 2026-01-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="e.g., 'Class 10'", max_length=100),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'C10'", max_length=20, unique=True
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., '2024-25'", max_length=10),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "db_table": "classes",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'A', 'B', 'Science'", max_length=50
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="e.g., '10-A', '10-B'", max_length=20),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True, help_text="Maximum students allowed", null=True
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "db_table": "sections",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="e.g., 'Mathematics'", max_length=100),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'MATH'", max_length=20, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("elective", "Elective"),
                            ("optional", "Optional"),
                        ],
                        help_text="Subject type",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "max_marks",
                    models.IntegerField(
                        default=100, help_text="Default maximum marks for exams"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="SubjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., '2024-25'", max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Assignment",
                "verbose_name_plural": "Subject Assignments",
                "db_table": "subject_assignments",
            },
        ),
    ]
