# Generated by Django 5.0.14 on 2026-01-15 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="academic.class",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="academic.class",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="academic.section",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="subject_assignments",
                to="accounts.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["code"], name="classes_code_674040_idx"),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["academic_year"], name="classes_academi_fdbba0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["status"], name="classes_status_ae471a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("code", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["class_obj"], name="sections_class_o_6939dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["code"], name="sections_code_d4cdf2_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["status"], name="sections_status_1b1ea0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("class_obj", "code")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["code"], name="subjects_code_3f80fa_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["type"], name="subjects_type_df9a27_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["status"], name="subjects_status_6bd3b8_idx"),
        ),
        migrations.AddIndex(
            model_name="subjectassignment",
            index=models.Index(
                fields=["class_obj", "section"], name="subject_ass_class_o_e1ce4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectassignment",
            index=models.Index(
                fields=["teacher"], name="subject_ass_teacher_424daf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectassignment",
            index=models.Index(
                fields=["subject"], name="subject_ass_subject_d3b52e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectassignment",
            index=models.Index(
                fields=["academic_year"], name="subject_ass_academi_09aa78_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectassignment",
            unique_together={("class_obj", "section", "subject", "academic_year")},
        ),
    ]
