# Generated by Django 5.0.14 on 2026-01-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='class',
            name='classes_code_674040_idx',
        ),
        migrations.RemoveIndex(
            model_name='class',
            name='classes_academi_fdbba0_idx',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='sections_class_o_6939dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='sections_code_d4cdf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subjects_code_3f80fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectassignment',
            name='subject_ass_class_o_e1ce4a_idx',
        ),
    ]
