# Generated by Django 5.0.14 on 2026-01-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_class_classes_code_674040_idx_and_more'),
        ('accounts', '0002_remove_schoolprofile_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(help_text="e.g., 'C10'", max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text="e.g., 'MATH'", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'code', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school', 'class_obj', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('school', 'class_obj', 'section', 'subject', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'code'], name='classes_school__8805fc_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'academic_year'], name='classes_school__ab7f87_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'class_obj'], name='sections_school__fd45f5_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'code'], name='sections_school__1087ba_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'code'], name='subjects_school__80e723_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['school', 'class_obj', 'section'], name='subject_ass_school__c5a0b9_idx'),
        ),
    ]
