# Generated by Django 5.0.14 on 2026-01-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0004_alter_class_unique_together_and_more"),
        ("accounts", "0002_remove_schoolprofile_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Class teacher assigned to this section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_teacher_of",
                to="accounts.teacherprofile",
            ),
        ),
    ]
