# Generated by Django 5.0.14 on 2026-01-20 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0005_section_class_teacher"),
        ("accounts", "0003_alter_user_managers_teacherprofile_subjects_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Period 1', 'Lunch Break'", max_length=100
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "is_break",
                    models.BooleanField(
                        default=False, help_text="If True, no classes are scheduled"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=1, help_text="Ordering for display"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="School this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.school",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "db_table": "periods",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., '2024-25'", max_length=10),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academic.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academic.period",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="School this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.school",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academic.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="accounts.teacherprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
                "db_table": "timetable_entries",
            },
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(
                fields=["school", "order"], name="periods_school__e40e81_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("school", "name"), ("school", "order")},
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["school", "class_obj", "section"],
                name="timetable_e_school__c33e6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["teacher"], name="timetable_e_teacher_3b88ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["day_of_week", "period"], name="timetable_e_day_of__20ea46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["academic_year"], name="timetable_e_academi_91b677_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together={
                ("school", "section", "day_of_week", "period", "academic_year")
            },
        ),
    ]
