# Generated by Django 5.0.14 on 2026-01-28 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0006_period_timetableentry_and_more"),
        ("accounts", "0005_alter_school_created_by_alter_school_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="class",
            name="classes_status_ae471a_idx",
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional head teacher/coordinator for this class",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_coordinator_of",
                to="accounts.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="max_marks",
            field=models.IntegerField(
                default=100,
                help_text="Maximum marks for this specific class assignment",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["status", "class_teacher"], name="classes_status_ab3686_idx"
            ),
        ),
    ]
